# Generated by Django 5.0.2 on 2025-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('solved', 'Solved')], default='processing', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profile_photos/')),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('address', models.TextField()),
                ('state', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('department', models.CharField(choices=[('Construction Workers', 'Construction Workers'), ('Textiles and Garments', 'Textiles and Garments'), ('Domestic Work and Housekeeping', 'Domestic Work and Housekeeping'), ('Retail and Sales', 'Retail and Sales'), ('Vendors', 'Vendors'), ('Security', 'Security'), ('Mining', 'Mining'), ('Factories', 'Factories')], max_length=50)),
                ('bank', models.CharField(max_length=30)),
                ('current_location', models.CharField(max_length=100)),
                ('working_state', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.PositiveIntegerField()),
                ('district', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('salary', models.PositiveIntegerField()),
                ('vaccine', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('employer', models.TextField()),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed')], max_length=10)),
            ],
        ),
    ]
